# Generated by Django 3.2 on 2022-09-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_personalcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
