# Generated by Django 3.2 on 2022-09-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_workcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
